{% set name = "google-re2" %}
{% set version = "1.1.20250722" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5e2a464df75dbcef9fe0daf18a78f73c3f0a51b81cdb865460a0579b226f2ef3

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11
    - pip
    - re2
    - setuptools
  run:
    - python
  run_constrained:
    # pyre2 is a different package for providing the google re2 python bindings
    - pyre2 ==9999999999

test:
  imports:
    - re2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/re2/tree/main/python
  summary: RE2 Python bindings
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/google/re2

extra:
  recipe-maintainers:
    - xylar
