{% set name = "google-re2" %}
{% set version = "1.1.20240601" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3187f68855307754d49f398e583853d5b08d783d3fe662f6916b999075f7e095

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11
    - pip
    - re2
  run:
    - python
  run_constrained:
    # pyre2 is a different package for providing the google re2 python bindings
    - pyre2 ==9999999999

test:
  imports:
    - re2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/re2/tree/main/python
  summary: RE2 Python bindings
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/google/re2

extra:
  recipe-maintainers:
    - xylar
